# Generated by Django 5.1.4 on 2025-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project2desc',
            field=models.TextField(default='No project to describe'),
        ),
        migrations.AddField(
            model_name='student',
            name='project2guide',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='project2name',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
