# Generated by Django 5.1.4 on 2025-01-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211013_1459'),
        ('app', '0002_rename_post_student'),
    ]

    operations = [
    ]
