# Generated by Django 5.1.4 on 2025-01-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_project2desc_student_project2guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project2guide',
        ),
        migrations.RemoveField(
            model_name='student',
            name='projectguide',
        ),
    ]
