# Generated by Django 5.1.4 on 2025-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_project2guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clgcpi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cls10cpi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cls12cpi',
        ),
        migrations.AddField(
            model_name='student',
            name='clgdept',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='cls10group',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='cls12group',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
